name: Build and Publish Docker Image
on:
    workflow_dispatch:
    push:
        branches:
          - main
        paths:
          - Dockerfile

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.9.0

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3.3.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GH_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6.13.0
              with:
                context: .
                file: Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                build-args: |
                  GITHUB_REPOSITORY=${{ github.repository }}
                  GITHUB_SHA=${{ github.sha }}
                tags: |
                  ghcr.io/${{ github.repository }}:latest
                  ghcr.io/${{ github.repository }}:${{ env.NODE_RED_VERSION }}
